theme: jekyll-theme-minimal
title: Hello there!
author: Jes&uacute;s-Javier Chi-Dom&iacute;nguez
description: Jes&uacute;s-Javier Chi-Dom&iacute;nguez
logo: "images/hereiam.jpg"
links:
        - label:        "Email"
          icon:         "&#x1F4E7;"
          url:          "mailto:chidoys@gmail.com"
