theme: jekyll-theme-minimal
title: Hello there!
description: Jes&uacute;s-Javier Chi-Dom&iacute;nguez

goals_page:
        title: title goes hered
        escription: description goes here

logo: "images/hereiam.jpg"
